### ISSUE TITLE
not support safari

### ISSUE THREAD

**Issue by fnagtaoch** [icepy/loseYourself#2]
under safari:
1.middle line show mistake,
2.can't scroll.
3.after first time click yes, if we change another value, it is close auto by it self(button-yes is not work)

**Comment by icepy** [comment]
what's safari version?

**Comment by icepy** [comment]
@fnagtaoch  i try test your question

1.this is css question to safari 
2.why can't scroll , because not mobile safari and i used touch events
3.button-yes is your add 'click' event, so your must in `valueChange` callback set value

``` JavaScript

var data = [
    {id:123},
    {id:456}
]
//the first value
var value = data[0];
var yes = document.getElementById('button-yes');
yes.addEventListener('click',function(){
   console.log(value)
});
UIPickerView.createPickerView({
   dataSource: data,
   id: 'provincePicker',
  constraintsId: 'wower',
  kUP: {
     kUPCELLHEIGHT: 26,
     kUPFRICTION: 0.003
 },
 valueChange: function(data) {
   // set your value
   value = data;
 }
});
```

**Comment by fnagtaoch** [comment]
Thank you for you answer!

yes .i just test on PC, not on mobile!
