### ISSUE TITLE
创建pickerveiw失败

### ISSUE THREAD

**Issue by Silencewanghui** [icepy/loseYourself#3]
点击“确定“或“取消”后，下一次的创建pickerveiw会不成功，等到创建成功时，滑动一次pickerview就会消失

**Comment by icepy** [comment]
那个只是演示Demo，实例只需要创建一次，如果你有多个，那么你需要分开创建不同的pickerview实例，然后再多个不同的确定和取消按钮中调用彼此不同的pickerview实例。
